// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Sadie Forbes

// Block definitions: named collections of geometry that INSERT places copies of.
//
// Split out of database.hpp for the same reason tables.hpp was -- undo.hpp has
// to name a block definition to journal one, and the two headers must not
// include each other.
//
// STORAGE. A definition owns its entities outright. They are not in the drawing
// order and have no database handles: a block's contents are not in the drawing,
// only its insertions are. That is what stops a block's geometry being picked,
// erased or written to the ENTITIES section in its own right.
//
// STABLE ADDRESSES. The table hands out `const BlockDef*` and never invalidates
// one, which is why it holds unique_ptrs rather than definitions by value. An
// Insert keeps that pointer instead of looking its block up by name on every
// draw -- and it has to, because `osnap_points()` and `draw()` are handed no
// database and could not perform the lookup even if it were cheap.
//
// It also buys R12's redefinition behaviour for free: BLOCK on an existing name
// rewrites the definition in place, and every insertion of it updates, because
// they all point at the same definition rather than holding copies.
#pragma once

#include "noto/entity.hpp"

#include <memory>
#include <string>
#include <vector>

namespace noto {

using BlockId = std::uint16_t;
inline constexpr BlockId kInvalidBlock = 0xFFFF;

// How deep INSERTs may nest before the kernel stops descending.
//
// R12 allows nested blocks and does not, in practice, allow cycles -- a block
// cannot contain an insertion of itself, because it does not exist yet when it
// is being defined. This guard exists for files that arrive claiming otherwise:
// a DXF is data from elsewhere, and a cycle in it must cost a truncated drawing
// rather than a stack overflow.
inline constexpr int kMaxBlockDepth = 32;

struct BlockDef {
    std::string name;

    // DXF group 10 of the BLOCK record: the point in the definition's own
    // coordinates that an insertion places at the insertion point.
    Vec3 base{};

    // Owned. Not database entities: no handles, not in the drawing order.
    std::vector<EntityPtr> entities;

    // DXF group 70. Bit 1 is anonymous, bit 2 has attributes, bits 4 and 8 are
    // external references. Kept whole so a round trip does not drop what this
    // program has no use for yet.
    std::int16_t flags{0};

    // R12 names blocks generated by other commands `*U1`, `*U2` and so on, and
    // hides them from the block list. Nothing generates one yet; the flag is
    // here because DXF carries it and dropping it would rename someone's block
    // on the way through.
    bool anonymous() const { return (flags & 1) != 0; }

    // Deep copy. Needed because the entities are unique_ptrs, so the struct is
    // move-only and the journal has to be able to keep a before-image.
    BlockDef clone() const;
};

}  // namespace noto
